import { Check, ChevronDown } from 'lucide-react';
import type { GuidedPlan, GuidedSessionDraft } from './types';
import { SemanticSlider } from './SemanticSlider';
import { SymptomPicker } from './SymptomPicker';
import { AppSelect } from '@/src/components/atal/AppSelect';

export function SessionClose({ plan, draft, onChange, onFinish }: { plan: GuidedPlan; draft: GuidedSessionDraft; onChange: (draft: GuidedSessionDraft) => void; onFinish: () => void }) {
  const [first, ...rest] = plan.exercises;
  const options = ['Sin especificar', first.name, ...rest.map((exercise) => exercise.name)];
  return <section className="atal-session-card atal-session-close"><span className="atal-session-kicker">Cierre de sesión</span><h1>Terminaste los ejercicios</h1><p>Registra cómo te sientes ahora. Ningún detalle adicional es obligatorio.</p><div className="atal-session-sliders"><SemanticSlider label="Dolor al finalizar" value={draft.end.pain} onChange={(pain) => onChange({ ...draft, end: { ...draft.end, pain } })} /><SemanticSlider label="Energía final" scale="energy" value={draft.end.energy} onChange={(energy) => onChange({ ...draft, end: { ...draft.end, energy } })} /><SemanticSlider label="Esfuerzo general" value={draft.end.effort} min={1} max={5} onChange={(effort) => onChange({ ...draft, end: { ...draft.end, effort } })} /></div><div className="atal-close-symptoms"><span>Síntomas durante la sesión</span><SymptomPicker value={draft.end.symptoms} onChange={(symptoms) => onChange({ ...draft, end: { ...draft.end, symptoms } })} /></div><label className="atal-session-comment"><span>Comentario final</span><textarea value={draft.end.comment} onChange={(event) => onChange({ ...draft, end: { ...draft.end, comment: event.target.value } })} placeholder="¿Cómo te fue hoy?" /></label><details className="atal-more-details"><summary>Agregar más detalles <ChevronDown /></summary><div>{[['easiest','Ejercicio más fácil'],['hardest','Ejercicio más difícil'],['discomfort','Ejercicio que causó molestia']].map(([key, label]) => <label key={key}><span>{label}</span><AppSelect label={label} value={draft.end[key as 'easiest'] || 'Sin especificar'} options={options} onChange={(value) => onChange({ ...draft, end: { ...draft.end, [key]: value === 'Sin especificar' ? '' : value } })} /></label>)}</div></details><button type="button" className="atal-session-primary" onClick={onFinish}><Check /> Finalizar sesión</button><small className="atal-local-save-copy">El resumen se guardará en este dispositivo. No se enviará a un fisioterapeuta.</small></section>;
}
