import type { ManualCapability } from './capabilityCatalog';

const common = {
  confirmation: 'explicit-request' as const,
  audit: 'activity-event' as const,
  undo: 'manual-compensation' as const,
};

function capability(row: ManualCapability): ManualCapability {
  return Object.freeze(row);
}

export const manualCapabilityInventory: ManualCapability[] = [
  capability({ id: 'patient.list-search', domain: 'patients', label: 'Listar y buscar pacientes', route: '/patients', manualEntryPoint: 'src/data/atalStore.ts#getAtalState', canonicalPersistence: ['patients'], currentTests: ['tests/foundation.test.mjs'], risk: 'read', confirmation: 'none', audit: 'none', undo: 'not-applicable', multimodal: ['text', 'audio'] }),
  capability({ id: 'patient.read', domain: 'patients', label: 'Consultar perfil de paciente', route: '/patients/:id', manualEntryPoint: 'src/screens/PatientProfileScreen.tsx#PatientProfileScreen', canonicalPersistence: ['patients', 'notes', 'plans', 'sessions'], currentTests: ['tests/foundation.test.mjs'], risk: 'read', confirmation: 'none', audit: 'none', undo: 'not-applicable', multimodal: ['text', 'audio'] }),
  capability({ id: 'patient.create', domain: 'patients', label: 'Crear paciente y expediente inicial', route: '/patients/new', manualEntryPoint: 'src/data/atalStore.ts#createPatientWithRecord', canonicalPersistence: ['patients', 'clinicalRecords', 'events'], currentTests: ['tests/foundation.test.mjs'], risk: 'reversible-write', confirmation: common.confirmation, audit: common.audit, undo: common.undo, multimodal: ['text', 'audio', 'image', 'pdf'] }),
  capability({ id: 'patient.update-demographics', domain: 'patients', label: 'Actualizar datos generales del paciente', route: '/patients/:id', manualEntryPoint: 'src/data/atalStore.ts#updatePatient', canonicalPersistence: ['patients', 'events'], currentTests: ['tests/foundation.test.mjs'], risk: 'reversible-write', confirmation: common.confirmation, audit: common.audit, undo: common.undo, multimodal: ['text', 'audio', 'image', 'pdf'] }),
  capability({ id: 'patient.update-contact', domain: 'patients', label: 'Actualizar teléfono, correo, dirección y contacto responsable', route: '/patients/:id', manualEntryPoint: 'src/data/atalStore.ts#updatePatient', canonicalPersistence: ['patients', 'events'], currentTests: ['tests/foundation.test.mjs'], risk: 'reversible-write', confirmation: common.confirmation, audit: common.audit, undo: common.undo, multimodal: ['text', 'audio', 'image', 'pdf'] }),
  capability({ id: 'patient.archive-restore', domain: 'patients', label: 'Archivar o restaurar paciente', route: '/patients/:id', manualEntryPoint: 'src/data/atalStore.ts#setPatientArchived', canonicalPersistence: ['patients', 'plans', 'events'], currentTests: ['tests/foundation.test.mjs'], risk: 'sensitive-write', confirmation: 'short-confirmation', audit: common.audit, undo: common.undo, multimodal: ['text', 'audio'] }),
  capability({ id: 'patient-note.create', domain: 'patients', label: 'Añadir nota al paciente', route: '/patients/:id', manualEntryPoint: 'src/data/atalStore.ts#addPatientNote', canonicalPersistence: ['notes', 'events'], currentTests: ['tests/atal-ai-core-tools.test.mjs'], risk: 'reversible-write', confirmation: common.confirmation, audit: 'transaction-event', undo: 'validated-receipt', multimodal: ['text', 'audio', 'image', 'pdf'] }),
  capability({ id: 'patient-note.update', domain: 'patients', label: 'Editar nota del paciente', route: '/patients/:id', manualEntryPoint: 'src/data/atalStore.ts#updatePatientNote', canonicalPersistence: ['notes'], currentTests: ['tests/foundation.test.mjs'], risk: 'reversible-write', confirmation: common.confirmation, audit: 'none', undo: common.undo, multimodal: ['text', 'audio'] }),
  capability({ id: 'patient-note.delete', domain: 'patients', label: 'Eliminar nota del paciente', route: '/patients/:id', manualEntryPoint: 'src/data/atalStore.ts#deletePatientNote', canonicalPersistence: ['notes'], currentTests: ['tests/foundation.test.mjs'], risk: 'destructive', confirmation: 'reinforced-confirmation', audit: 'none', undo: 'not-supported', multimodal: ['text', 'audio'] }),

  capability({ id: 'clinical-record.read', domain: 'clinical-records', label: 'Consultar expediente clínico', route: '/patients/:id/clinical-record', manualEntryPoint: 'src/features/clinical-record/ClinicalRecordScreen.tsx#ClinicalRecordScreen', canonicalPersistence: ['clinicalRecords'], currentTests: ['tests/foundation.test.mjs'], risk: 'read', confirmation: 'none', audit: 'none', undo: 'not-applicable', multimodal: ['text', 'audio'] }),
  capability({ id: 'clinical-record.create', domain: 'clinical-records', label: 'Crear expediente clínico', route: '/patients/:id/clinical-record', manualEntryPoint: 'src/data/atalStore.ts#saveClinicalRecord', canonicalPersistence: ['clinicalRecords', 'events'], currentTests: ['tests/foundation.test.mjs'], risk: 'reversible-write', confirmation: common.confirmation, audit: common.audit, undo: common.undo, multimodal: ['text', 'audio', 'image', 'pdf'] }),
  capability({ id: 'clinical-record.update', domain: 'clinical-records', label: 'Actualizar expediente y crear versión', route: '/patients/:id/clinical-record', manualEntryPoint: 'src/data/atalStore.ts#saveClinicalRecord', canonicalPersistence: ['clinicalRecords', 'clinicalRecordVersions', 'events'], currentTests: ['tests/clinical-record-pain-level.test.mjs'], risk: 'reversible-write', confirmation: common.confirmation, audit: 'transaction-event', undo: 'validated-receipt', multimodal: ['text', 'audio', 'image', 'pdf'] }),
  capability({ id: 'clinical-record.read-history', domain: 'clinical-records', label: 'Consultar versiones anteriores del expediente', route: '/patients/:id/clinical-record', manualEntryPoint: 'src/data/atalStore.ts#getAtalState', canonicalPersistence: ['clinicalRecordVersions'], currentTests: ['tests/foundation.test.mjs'], risk: 'read', confirmation: 'none', audit: 'none', undo: 'not-applicable', multimodal: ['text', 'audio'] }),

  capability({ id: 'plan.list-search', domain: 'plans', label: 'Listar y filtrar planes', route: '/plans', manualEntryPoint: 'src/data/atalStore.ts#getAtalState', canonicalPersistence: ['plans'], currentTests: ['tests/foundation.test.mjs'], risk: 'read', confirmation: 'none', audit: 'none', undo: 'not-applicable', multimodal: ['text', 'audio'] }),
  capability({ id: 'plan.read', domain: 'plans', label: 'Consultar plan y prescripción', route: '/plans/:id', manualEntryPoint: 'src/screens/PlanDetailCloseoutScreen.tsx#PlanDetailCloseoutScreen', canonicalPersistence: ['plans', 'exercises'], currentTests: ['tests/foundation.test.mjs'], risk: 'read', confirmation: 'none', audit: 'none', undo: 'not-applicable', multimodal: ['text', 'audio'] }),
  capability({ id: 'plan.create', domain: 'plans', label: 'Crear plan para paciente', route: '/plans/new', manualEntryPoint: 'src/data/atalStore.ts#createPlan', canonicalPersistence: ['plans', 'clinicalRecords', 'events'], currentTests: ['tests/atal-ai-core-tools.test.mjs'], risk: 'reversible-write', confirmation: common.confirmation, audit: 'transaction-event', undo: 'validated-receipt', multimodal: ['text', 'audio', 'image', 'pdf'] }),
  capability({ id: 'plan.update', domain: 'plans', label: 'Editar plan clínico', route: '/plans/:id', manualEntryPoint: 'src/data/atalStore.ts#updatePlan', canonicalPersistence: ['plans', 'events'], currentTests: ['tests/atal-ai-core-tools.test.mjs'], risk: 'reversible-write', confirmation: common.confirmation, audit: 'transaction-event', undo: 'validated-receipt', multimodal: ['text', 'audio', 'image', 'pdf'] }),
  capability({ id: 'plan.duplicate', domain: 'plans', label: 'Duplicar plan como borrador', route: '/plans/:id', manualEntryPoint: 'src/data/atalStore.ts#duplicatePlan', canonicalPersistence: ['plans', 'events'], currentTests: ['tests/foundation.test.mjs'], risk: 'reversible-write', confirmation: common.confirmation, audit: common.audit, undo: common.undo, multimodal: ['text', 'audio'] }),
  capability({ id: 'plan.delete-safe', domain: 'plans', label: 'Eliminar plan sin sesiones', route: '/plans/:id', manualEntryPoint: 'src/data/atalStore.ts#deletePlan', canonicalPersistence: ['plans'], currentTests: ['tests/foundation.test.mjs'], risk: 'destructive', confirmation: 'reinforced-confirmation', audit: 'none', undo: 'not-supported', multimodal: ['text', 'audio'] }),
  capability({ id: 'plan.activate', domain: 'plans', label: 'Activar plan', route: '/plans/:id', manualEntryPoint: 'src/data/atalStore.ts#updatePlanStatus', canonicalPersistence: ['plans', 'events', 'notifications'], currentTests: ['tests/atal-ai-core-tools.test.mjs'], risk: 'sensitive-write', confirmation: 'short-confirmation', audit: 'transaction-event', undo: 'validated-receipt', multimodal: ['text', 'audio'] }),
  capability({ id: 'plan.pause', domain: 'plans', label: 'Pausar plan activo', route: '/plans/:id', manualEntryPoint: 'src/data/atalStore.ts#updatePlanStatus', canonicalPersistence: ['plans', 'events'], currentTests: ['tests/atal-ai-core-tools.test.mjs'], risk: 'reversible-write', confirmation: common.confirmation, audit: 'transaction-event', undo: 'validated-receipt', multimodal: ['text', 'audio'] }),
  capability({ id: 'plan.complete', domain: 'plans', label: 'Completar plan', route: '/plans/:id', manualEntryPoint: 'src/data/atalStore.ts#updatePlanStatus', canonicalPersistence: ['plans', 'events'], currentTests: ['tests/atal-ai-core-tools.test.mjs'], risk: 'sensitive-write', confirmation: 'short-confirmation', audit: 'transaction-event', undo: 'validated-receipt', multimodal: ['text', 'audio'] }),
  capability({ id: 'plan.archive-restore', domain: 'plans', label: 'Archivar o restaurar plan', route: '/plans/:id', manualEntryPoint: 'src/data/atalStore.ts#updatePlanStatus', canonicalPersistence: ['plans', 'events'], currentTests: ['tests/atal-ai-core-tools.test.mjs'], risk: 'sensitive-write', confirmation: 'short-confirmation', audit: 'transaction-event', undo: 'validated-receipt', multimodal: ['text', 'audio'] }),
  capability({ id: 'plan.replace-active', domain: 'plans', label: 'Reemplazar plan activo de forma atómica', route: '/plans/:id', manualEntryPoint: 'src/data/atalStore.ts#updatePlanStatus', canonicalPersistence: ['plans', 'events', 'notifications'], currentTests: ['tests/atal-ai-core-tools.test.mjs'], risk: 'sensitive-write', confirmation: 'short-confirmation', audit: 'transaction-event', undo: 'validated-receipt', multimodal: ['text', 'audio'] }),
  capability({ id: 'plan.add-exercises', domain: 'plans', label: 'Añadir ejercicios al plan', route: '/plans/:id', manualEntryPoint: 'src/data/atalStore.ts#updatePlan', canonicalPersistence: ['plans'], currentTests: ['tests/foundation.test.mjs'], risk: 'reversible-write', confirmation: common.confirmation, audit: common.audit, undo: common.undo, multimodal: ['text', 'audio', 'image', 'pdf'] }),
  capability({ id: 'plan.remove-exercises', domain: 'plans', label: 'Retirar ejercicios del plan', route: '/plans/:id', manualEntryPoint: 'src/data/atalStore.ts#updatePlan', canonicalPersistence: ['plans'], currentTests: ['tests/foundation.test.mjs'], risk: 'reversible-write', confirmation: common.confirmation, audit: common.audit, undo: common.undo, multimodal: ['text', 'audio'] }),
  capability({ id: 'plan.reorder-exercises', domain: 'plans', label: 'Reordenar ejercicios del plan', route: '/plans/:id', manualEntryPoint: 'src/data/atalStore.ts#updatePlan', canonicalPersistence: ['plans'], currentTests: ['tests/foundation.test.mjs'], risk: 'reversible-write', confirmation: common.confirmation, audit: common.audit, undo: common.undo, multimodal: ['text', 'audio'] }),

  capability({ id: 'exercise.list-search', domain: 'exercises', label: 'Listar, buscar y filtrar ejercicios', route: '/exercises', manualEntryPoint: 'src/data/atalStore.ts#getAtalState', canonicalPersistence: ['exercises'], currentTests: ['tests/foundation.test.mjs'], risk: 'read', confirmation: 'none', audit: 'none', undo: 'not-applicable', multimodal: ['text', 'audio', 'image'] }),
  capability({ id: 'exercise.read', domain: 'exercises', label: 'Consultar ejercicio y prescripción', route: '/exercises/:id', manualEntryPoint: 'src/screens/ExerciseDetailScreen.tsx#ExerciseDetailScreen', canonicalPersistence: ['exercises'], currentTests: ['tests/foundation.test.mjs'], risk: 'read', confirmation: 'none', audit: 'none', undo: 'not-applicable', multimodal: ['text', 'audio', 'image'] }),
  capability({ id: 'exercise.create', domain: 'exercises', label: 'Crear ejercicio', route: '/exercises/new', manualEntryPoint: 'src/data/atalStore.ts#createExercise', canonicalPersistence: ['exercises', 'events'], currentTests: ['tests/atal-ai-core-tools.test.mjs'], risk: 'reversible-write', confirmation: common.confirmation, audit: 'transaction-event', undo: 'validated-receipt', multimodal: ['text', 'audio', 'image', 'pdf'] }),
  capability({ id: 'exercise.update', domain: 'exercises', label: 'Editar ejercicio', route: '/exercises/:id', manualEntryPoint: 'src/data/atalStore.ts#updateExercise', canonicalPersistence: ['exercises'], currentTests: ['tests/atal-ai-core-tools.test.mjs'], risk: 'reversible-write', confirmation: common.confirmation, audit: 'transaction-event', undo: 'validated-receipt', multimodal: ['text', 'audio', 'image', 'pdf'] }),
  capability({ id: 'exercise.duplicate', domain: 'exercises', label: 'Duplicar ejercicio', route: '/exercises/:id', manualEntryPoint: 'src/data/atalStore.ts#duplicateExercise', canonicalPersistence: ['exercises', 'events'], currentTests: ['tests/foundation.test.mjs'], risk: 'reversible-write', confirmation: common.confirmation, audit: common.audit, undo: common.undo, multimodal: ['text', 'audio'] }),
  capability({ id: 'exercise.archive-restore', domain: 'exercises', label: 'Archivar o restaurar ejercicio', route: '/exercises/:id', manualEntryPoint: 'src/data/atalStore.ts#archiveExercise', canonicalPersistence: ['exercises'], currentTests: ['tests/foundation.test.mjs'], risk: 'reversible-write', confirmation: common.confirmation, audit: 'none', undo: common.undo, multimodal: ['text', 'audio'] }),
  capability({ id: 'exercise.delete-safe', domain: 'exercises', label: 'Eliminar ejercicio no asociado', route: '/exercises/:id', manualEntryPoint: 'src/data/atalStore.ts#deleteExercise', canonicalPersistence: ['exercises'], currentTests: ['tests/foundation.test.mjs'], risk: 'destructive', confirmation: 'reinforced-confirmation', audit: 'none', undo: 'not-supported', multimodal: ['text', 'audio'] }),
  capability({ id: 'exercise.update-media', domain: 'exercises', label: 'Añadir o sustituir multimedia del ejercicio', route: '/exercises/:id', manualEntryPoint: 'src/data/exerciseMediaRepository.ts#saveExerciseMedia', canonicalPersistence: ['exercises', 'IndexedDB media'], currentTests: ['tests/foundation.test.mjs'], risk: 'reversible-write', confirmation: 'compact-review', audit: 'none', undo: common.undo, multimodal: ['image'] }),

  capability({ id: 'session.prepare', domain: 'sessions', label: 'Preparar sesión guiada desde plan activo', route: '/patients/:id/session', manualEntryPoint: 'src/features/guided-session/planResolver.ts#resolvePatientPlan', canonicalPersistence: ['guided session draft'], currentTests: ['tests/foundation.test.mjs'], risk: 'read', confirmation: 'none', audit: 'none', undo: 'not-applicable', multimodal: ['text', 'audio'] }),
  capability({ id: 'session.start-resume', domain: 'sessions', label: 'Iniciar o reanudar sesión guiada', route: '/patients/:id/session', manualEntryPoint: 'src/features/guided-session/sessionRepository.ts#recordClinicalSessionStarted', canonicalPersistence: ['events', 'guided session draft'], currentTests: ['tests/foundation.test.mjs'], risk: 'reversible-write', confirmation: common.confirmation, audit: common.audit, undo: 'not-supported', multimodal: ['text', 'audio'] }),
  capability({ id: 'session.record-exercise-result', domain: 'sessions', label: 'Registrar resultado de cada ejercicio', route: '/patients/:id/session', manualEntryPoint: 'src/features/guided-session/GuidedSessionFlow.tsx#GuidedSessionFlow', canonicalPersistence: ['guided session draft'], currentTests: ['tests/foundation.test.mjs'], risk: 'reversible-write', confirmation: common.confirmation, audit: 'none', undo: common.undo, multimodal: ['text', 'audio', 'image'] }),
  capability({ id: 'session.record-symptoms', domain: 'sessions', label: 'Registrar dolor, energía, esfuerzo y síntomas', route: '/patients/:id/session', manualEntryPoint: 'src/features/guided-session/GuidedSessionFlow.tsx#GuidedSessionFlow', canonicalPersistence: ['guided session draft'], currentTests: ['tests/foundation.test.mjs'], risk: 'reversible-write', confirmation: common.confirmation, audit: 'none', undo: common.undo, multimodal: ['text', 'audio'] }),
  capability({ id: 'session.complete', domain: 'sessions', label: 'Completar o guardar sesión parcial', route: '/patients/:id/session', manualEntryPoint: 'src/features/guided-session/sessionRepository.ts#saveCompletedClinicalSession', canonicalPersistence: ['sessions', 'events', 'notifications'], currentTests: ['tests/foundation.test.mjs'], risk: 'sensitive-write', confirmation: 'short-confirmation', audit: common.audit, undo: 'not-supported', multimodal: ['text', 'audio'] }),

  capability({ id: 'report.list', domain: 'reports-activity', label: 'Listar actividad y reportes', route: '/activity', manualEntryPoint: 'src/data/atalStore.ts#getAtalState', canonicalPersistence: ['events', 'sessions'], currentTests: ['tests/foundation.test.mjs'], risk: 'read', confirmation: 'none', audit: 'none', undo: 'not-applicable', multimodal: ['text', 'audio'] }),
  capability({ id: 'report.read', domain: 'reports-activity', label: 'Consultar reporte clínico de sesión', route: '/activity/:id', manualEntryPoint: 'src/screens/ActivityDetailScreen.tsx#ActivityDetailScreen', canonicalPersistence: ['sessions'], currentTests: ['tests/foundation.test.mjs'], risk: 'read', confirmation: 'none', audit: 'none', undo: 'not-applicable', multimodal: ['text', 'audio'] }),
  capability({ id: 'report.prepare-summary', domain: 'reports-activity', label: 'Preparar resumen de sesión', route: '/activity/:id', manualEntryPoint: 'src/features/atal-ai/core/tools/queryTools.ts#queryTools', canonicalPersistence: ['sessions'], currentTests: ['tests/atal-ai-core-tools.test.mjs'], risk: 'read', confirmation: 'none', audit: 'none', undo: 'not-applicable', multimodal: ['text', 'audio'] }),
  capability({ id: 'report.review', domain: 'reports-activity', label: 'Revisar reporte y guardar observación clínica', route: '/activity/:id', manualEntryPoint: 'src/data/atalStore.ts#reviewSession', canonicalPersistence: ['sessions', 'events', 'notifications'], currentTests: ['tests/foundation.test.mjs'], risk: 'reversible-write', confirmation: common.confirmation, audit: common.audit, undo: common.undo, multimodal: ['text', 'audio', 'image', 'pdf'] }),
  capability({ id: 'activity.read-audit', domain: 'reports-activity', label: 'Consultar historial y auditoría de Atal IA', route: '/activity', manualEntryPoint: 'src/data/atalStore.ts#getAtalState', canonicalPersistence: ['events'], currentTests: ['tests/atal-ai-core-transaction.test.mjs'], risk: 'read', confirmation: 'none', audit: 'none', undo: 'not-applicable', multimodal: ['text', 'audio'] }),

  capability({ id: 'delivery.preview', domain: 'delivery-exports', label: 'Previsualizar entrega del plan', route: '/plans/:id/delivery', manualEntryPoint: 'src/screens/PatientPlanDeliveryScreen.tsx#PatientPlanDeliveryScreen', canonicalPersistence: ['plans', 'patients', 'exercises'], currentTests: ['tests/foundation.test.mjs'], risk: 'read', confirmation: 'none', audit: 'none', undo: 'not-applicable', multimodal: ['text', 'audio'] }),
  capability({ id: 'delivery.configure', domain: 'delivery-exports', label: 'Configurar plan, registro y sesiones', route: '/plans/:id/delivery', manualEntryPoint: 'src/features/patient-delivery/deliveryOptions.ts#normalizePatientPlanDeliveryOptions', canonicalPersistence: ['delivery draft'], currentTests: ['tests/foundation.test.mjs'], risk: 'reversible-write', confirmation: common.confirmation, audit: 'none', undo: common.undo, multimodal: ['text', 'audio'] }),
  capability({ id: 'delivery.generate-pdf', domain: 'delivery-exports', label: 'Generar PDF local', route: '/plans/:id/delivery', manualEntryPoint: 'src/features/patient-delivery/pdfRouter.ts#createPatientPlanPdf', canonicalPersistence: ['local file'], currentTests: ['tests/foundation.test.mjs'], risk: 'sensitive-write', confirmation: 'short-confirmation', audit: 'client-effect-only', undo: 'not-supported', multimodal: ['text', 'audio'] }),
  capability({ id: 'delivery.download-print-share', domain: 'delivery-exports', label: 'Descargar, imprimir o compartir PDF', route: '/plans/:id/delivery', manualEntryPoint: 'src/screens/PatientPlanDeliveryScreen.tsx#PatientPlanDeliveryScreen', canonicalPersistence: ['local file'], currentTests: ['tests/foundation.test.mjs'], risk: 'external', confirmation: 'short-confirmation', audit: 'client-effect-only', undo: 'not-supported', multimodal: ['text', 'audio'] }),
  capability({ id: 'delivery.prepare-whatsapp', domain: 'delivery-exports', label: 'Preparar apertura de WhatsApp con mensaje', route: '/plans/:id/delivery', manualEntryPoint: 'src/features/patient-delivery/whatsapp.ts#createWhatsAppDeliveryUrl', canonicalPersistence: ['none'], currentTests: ['tests/foundation.test.mjs'], risk: 'external', confirmation: 'short-confirmation', audit: 'client-effect-only', undo: 'not-supported', multimodal: ['text', 'audio'] }),
  capability({ id: 'export.patients', domain: 'delivery-exports', label: 'Exportar pacientes', route: '/exports', manualEntryPoint: 'src/features/atal-ai/core/tools/exportTools.ts#exportTools', canonicalPersistence: ['local file'], currentTests: ['tests/atal-ai-core-tools.test.mjs'], risk: 'sensitive-write', confirmation: 'short-confirmation', audit: 'client-effect-only', undo: 'not-supported', multimodal: ['text', 'audio'] }),
  capability({ id: 'export.progress', domain: 'delivery-exports', label: 'Exportar progreso', route: '/exports', manualEntryPoint: 'src/features/atal-ai/core/tools/exportTools.ts#exportTools', canonicalPersistence: ['local file'], currentTests: ['tests/atal-ai-core-tools.test.mjs'], risk: 'sensitive-write', confirmation: 'short-confirmation', audit: 'client-effect-only', undo: 'not-supported', multimodal: ['text', 'audio'] }),
  capability({ id: 'export.plans-backup', domain: 'delivery-exports', label: 'Exportar planes o respaldo local', route: '/exports', manualEntryPoint: 'src/features/atal-ai/core/tools/exportTools.ts#exportTools', canonicalPersistence: ['local file'], currentTests: ['tests/atal-ai-core-tools.test.mjs'], risk: 'sensitive-write', confirmation: 'short-confirmation', audit: 'client-effect-only', undo: 'not-supported', multimodal: ['text', 'audio'] }),

  capability({ id: 'settings.read', domain: 'profile-settings', label: 'Consultar preferencias y perfil profesional', route: '/settings', manualEntryPoint: 'src/data/atalStore.ts#getAtalState', canonicalPersistence: ['settings'], currentTests: ['tests/foundation.test.mjs'], risk: 'read', confirmation: 'none', audit: 'none', undo: 'not-applicable', multimodal: ['text', 'audio'] }),
  capability({ id: 'settings.update-profile', domain: 'profile-settings', label: 'Actualizar perfil profesional', route: '/settings/profile', manualEntryPoint: 'src/data/atalStore.ts#updateSettings', canonicalPersistence: ['settings'], currentTests: ['tests/foundation.test.mjs'], risk: 'reversible-write', confirmation: common.confirmation, audit: common.audit, undo: common.undo, multimodal: ['text', 'audio', 'image'] }),
  capability({ id: 'settings.update-privacy', domain: 'profile-settings', label: 'Actualizar privacidad y bloqueo de sesión', route: '/settings/privacy', manualEntryPoint: 'src/data/atalStore.ts#updateSettings', canonicalPersistence: ['settings'], currentTests: ['tests/foundation.test.mjs'], risk: 'reversible-write', confirmation: common.confirmation, audit: common.audit, undo: common.undo, multimodal: ['text', 'audio'] }),
  capability({ id: 'settings.update-appearance', domain: 'profile-settings', label: 'Actualizar apariencia y densidad', route: '/settings/appearance', manualEntryPoint: 'src/context/ThemeContext.tsx#ThemeProvider', canonicalPersistence: ['theme preference', 'settings'], currentTests: ['tests/foundation.test.mjs'], risk: 'reversible-write', confirmation: common.confirmation, audit: 'none', undo: common.undo, multimodal: ['text', 'audio'] }),
  capability({ id: 'settings.update-ai-preferences', domain: 'profile-settings', label: 'Actualizar preferencias de Atal IA', route: '/settings/ai', manualEntryPoint: 'src/data/atalStore.ts#updateSettings', canonicalPersistence: ['settings'], currentTests: ['tests/atal-ai-core-tools.test.mjs'], risk: 'reversible-write', confirmation: common.confirmation, audit: 'transaction-event', undo: 'validated-receipt', multimodal: ['text', 'audio'] }),
  capability({ id: 'feedback.prepare-share', domain: 'profile-settings', label: 'Preparar y compartir comentario', route: '/settings/feedback', manualEntryPoint: 'src/data/atalStore.ts#addFeedback', canonicalPersistence: ['feedback'], currentTests: ['tests/foundation.test.mjs'], risk: 'external', confirmation: 'short-confirmation', audit: 'client-effect-only', undo: 'not-supported', multimodal: ['text', 'audio', 'image'] }),

  capability({ id: 'navigation.open-screen', domain: 'navigation-assistance', label: 'Abrir una pantalla o entidad solicitada', route: '*', manualEntryPoint: 'src/AppCloseout.tsx#PrivateAppRoutes', canonicalPersistence: ['none'], currentTests: ['e2e/block-4-1-critical.spec.mjs'], risk: 'read', confirmation: 'none', audit: 'none', undo: 'not-applicable', multimodal: ['text', 'audio'] }),
  capability({ id: 'navigation.open-contextual-assistant', domain: 'navigation-assistance', label: 'Abrir Atal IA con contexto actual', route: '*', manualEntryPoint: 'src/features/atal-ai/contextual/ContextualAIProvider.tsx#ContextualAIProvider', canonicalPersistence: ['AI conversations'], currentTests: ['e2e/block-4-2-contextual.spec.mjs'], risk: 'read', confirmation: 'none', audit: 'none', undo: 'not-applicable', multimodal: ['text', 'audio', 'image', 'pdf'] }),
  capability({ id: 'assistant.resume-task', domain: 'navigation-assistance', label: 'Reanudar conversación y tarea pendiente', route: '/assistant', manualEntryPoint: 'src/features/atal-ai/data/aiRepository.ts#getLatestAIConversation', canonicalPersistence: ['AI conversations', 'AI drafts'], currentTests: ['tests/foundation.test.mjs'], risk: 'read', confirmation: 'none', audit: 'none', undo: 'not-applicable', multimodal: ['text', 'audio', 'image', 'pdf'] }),
];
