'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { Check, LockKeyhole, Send, ShieldCheck } from 'lucide-react';
import { AtalLogo } from '@/src/components/atal/AtalLogo';

export function PortalCheckInScreen() {
  const router = useRouter();
  const [pain, setPain] = useState(4); const [mobility, setMobility] = useState(6); const [energy, setEnergy] = useState(7); const [adherence, setAdherence] = useState(8); const [comment, setComment] = useState(''); const [sent, setSent] = useState(false);
  if (sent) return <main className="atal-patient-portal atal-portal-confirmation"><AtalLogo /><span><Check /></span><h1>Reporte enviado</h1><p>Tu terapeuta podrá revisar cómo te sientes y ajustar tu plan.</p><button type="button" className="atal-portal-primary" onClick={() => router.push('/portal')}>Volver a mi plan</button></main>;
  return <main className="atal-patient-portal atal-checkin-page"><header><AtalLogo /><span><ShieldCheck /> Enlace seguro</span></header><section className="atal-checkin-heading"><small>Tu plan</small><h1>Rehabilitación — Fase 1</h1><p>Paciente Demo 01</p></section><section className="atal-checkin-form"><h2>Check-in de sesión</h2><p>Cuéntanos cómo te sientes hoy. Esto ayudará a tu terapeuta a ajustar tu plan.</p><CheckRange label="Dolor" low="Sin dolor" high="Dolor extremo" value={pain} onChange={setPain} /><CheckRange label="Movilidad" low="Muy limitada" high="Sin limitaciones" value={mobility} onChange={setMobility} /><CheckRange label="Energía" low="Muy baja" high="Muy alta" value={energy} onChange={setEnergy} /><CheckRange label="Adherencia" low="No completado" high="Completado siempre" value={adherence} onChange={setAdherence} /><label className="atal-checkin-comment"><span>Comentario breve</span><textarea maxLength={300} value={comment} onChange={(event) => setComment(event.target.value)} placeholder="¿Algo que quieras compartir sobre tu progreso, dolor o la sesión de hoy?" /><small>{comment.length}/300</small></label></section><button type="button" className="atal-portal-primary" onClick={() => setSent(true)}><Send /> Enviar reporte</button><button type="button" className="atal-portal-secondary" onClick={() => router.push('/portal')}>Omitir por ahora</button><footer><LockKeyhole /> Tu información está protegida y solo la verá tu terapeuta.</footer></main>;
}
function CheckRange({ label, low, high, value, onChange }: { label: string; low: string; high: string; value: number; onChange: (value: number) => void }) { return <label className="atal-check-range"><span><b>{label}</b><strong>{value} / 10</strong></span><small><i>{low}</i><i>{high}</i></small><input type="range" min="0" max="10" value={value} onChange={(event) => onChange(Number(event.target.value))} style={{ '--range': `${value*10}%` } as React.CSSProperties} /></label>; }
