'use client';
import { useState } from 'react';
import { ArrowLeft, Bot, Check, LockKeyhole, Moon, Save, ShieldCheck, Sun, UserRound, WandSparkles } from 'lucide-react';
import { useRouter } from 'next/navigation';
import { AtalShell } from '@/src/components/atal/AtalShell';
import { useTheme, type ThemeMode } from '@/src/context/ThemeContext';
export type SettingsKind='profile'|'privacy'|'ai'|'appearance';
const titles={profile:'Perfil profesional',privacy:'Privacidad y seguridad',ai:'Preferencias de Atal IA',appearance:'Apariencia'};
export function SettingsDetailScreen({kind}:{kind:SettingsKind}){const router=useRouter();return <AtalShell><main className="atal-content atal-flow-page atal-settings-detail"><div className="atal-flow-topbar"><button onClick={()=>router.back()}><ArrowLeft/></button><span>{titles[kind]}</span><i/></div>{kind==='profile'&&<Profile/>}{kind==='privacy'&&<Privacy/>}{kind==='ai'&&<AiPreferences/>}{kind==='appearance'&&<Appearance/>}</main></AtalShell>}
function SaveButton({saved,onClick}:{saved:boolean;onClick:()=>void}){return <button type="button" className="atal-settings-save" onClick={onClick}>{saved?<Check/>:<Save/>}{saved?'Cambios guardados':'Guardar cambios'}</button>}
function Profile(){const[name,setName]=useState('Cuenta demo');const[license,setLicense]=useState('Fisioterapeuta');const[saved,setSaved]=useState(false);return <><DetailHeading icon={<UserRound/>} title="Tu perfil profesional" text="Información visible dentro del espacio clínico."/><div className="atal-settings-form"><label><span>Nombre profesional</span><input value={name} onChange={e=>setName(e.target.value)}/></label><label><span>Especialidad</span><input value={license} onChange={e=>setLicense(e.target.value)}/></label><label><span>Centro o clínica</span><input placeholder="Clínica Atal"/></label></div><SaveButton saved={saved} onClick={()=>setSaved(true)}/></>}
function Privacy(){const[lock,setLock]=useState(true);const[clinical,setClinical]=useState(true);return <><DetailHeading icon={<ShieldCheck/>} title="Privacidad y seguridad" text="Controles locales preparados para la futura autenticación."/><div className="atal-settings-card"><LocalToggle icon={<LockKeyhole/>} title="Bloqueo de la sesión" detail="Solicitar acceso al volver a la app" value={lock} onChange={setLock}/><LocalToggle icon={<ShieldCheck/>} title="Datos clínicos privados" detail="El paciente solo accede a su propio plan" value={clinical} onChange={setClinical}/></div><div className="atal-role-note"><b>Separación de roles</b><p>El fisioterapeuta administra expedientes y previsualiza la experiencia del paciente. El paciente nunca ve el panel clínico.</p></div></>}
function AiPreferences(){const[suggestions,setSuggestions]=useState(true);const[alerts,setAlerts]=useState(true);return <><DetailHeading icon={<WandSparkles/>} title="Preferencias de Atal IA" text="Define cómo deberá acompañarte el asistente clínico."/><div className="atal-settings-card"><LocalToggle icon={<Bot/>} title="Sugerencias clínicas" detail="Propuestas locales dentro de planes" value={suggestions} onChange={setSuggestions}/><LocalToggle icon={<WandSparkles/>} title="Alertas inteligentes" detail="Señalar cambios que requieren revisión" value={alerts} onChange={setAlerts}/></div><label className="atal-settings-textarea"><span>Indicaciones para Atal IA</span><textarea defaultValue="Prioriza claridad, seguridad clínica y decisiones fáciles de revisar."/></label></>}
function Appearance(){const{mode,setMode}=useTheme();return <><DetailHeading icon={<Moon/>} title="Apariencia" text="Graphite Clinical es el modo oscuro oficial de Atal."/><div className="atal-theme-options"><ThemeOption mode="light" current={mode} title="Claro" detail="Marca oficial sobre blanco" icon={<Sun/>} onClick={setMode}/><ThemeOption mode="dark" current={mode} title="Graphite Clinical" detail="Oscuro clínico M080" icon={<Moon/>} onClick={setMode}/><ThemeOption mode="system" current={mode} title="Sistema" detail="Preferencia del dispositivo" icon={<WandSparkles/>} onClick={setMode}/></div></>}
function DetailHeading({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="atal-detail-heading"><span>{icon}</span><h1>{title}</h1><p>{text}</p></div>}
function ThemeOption({mode,current,title,detail,icon,onClick}:{mode:ThemeMode;current:ThemeMode;title:string;detail:string;icon:React.ReactNode;onClick:(mode:ThemeMode)=>void}){return <button type="button" className={mode===current?'is-active':''} onClick={()=>onClick(mode)}><span>{icon}</span><span><b>{title}</b><small>{detail}</small></span>{mode===current&&<Check/>}</button>}
function LocalToggle({icon,title,detail,value,onChange}:{icon:React.ReactNode;title:string;detail:string;value:boolean;onChange:(v:boolean)=>void}){return <button type="button" className="atal-settings-row" onClick={()=>onChange(!value)}><span>{icon}</span><span><b>{title}</b><small>{detail}</small></span><i className={value?'is-on':''}><em/></i></button>}
